#!/bin/sh
find /var/cache/apt/apt-file -name '*gz' -type f -print0 | \
	xargs -r0 zgrep -h '^usr\/bin\/\|^usr\/sbin\/\|^bin\/\|^sbin\/' | \
	awk '{sub(/.+\//,"",$1);printf("%s\t",$1);sub("$1","",$1);print}' | \
		cdb -c -m $HOME/.cache/command-not-found.cdb
